name: Run GnLBuildCred

on:
  push:
    branches:
      - main
  schedule:
     - cron: '*/5 3-10 * * 1-5'  # This cron schedule runs every 5 minutes Monday to Friday, from 9:15 AM to 3:30 PM IST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Remove conflicting logging package
        run: |
          pip uninstall -y logging || true

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip
      

      - name: Load environment variables
        run: |
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
          echo "PWD=${{ secrets.PWD }}" >> $GITHUB_ENV
          echo "TOTP_SECRET=${{ secrets.TOTP_SECRET }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "TOKEN_MAP=${{ secrets.TOKEN_MAP }}" >> $GITHUB_ENV
          echo "FEED_TOKEN=${{ secrets.FEED_TOKEN }}" >> $GITHUB_ENV
          echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> $GITHUB_ENV

      - name: Debug TOTP Key
        run: |
           echo "TOTP_KEY length: ${#TOTP_KEY}"
           echo "TOTP_KEY (masked): ${TOTP_KEY:0:4}******"

      - name: Debug environment variables
        run: env | grep -E 'USER_NAME|PWD|TOTP_SECRET|API_KEY|TOKEN_MAP|FEED_TOKEN|SHEET_ID'

      - name: Debug dependency tree
        run: |
          pip install pipdeptree
          pipdeptree

      - name: Install Python dependencies
        run: |
          pip install --no-cache-dir numpy
          pip install -r requirements.txt -c constraints.txt


      - name: Debug installed packages
        run: pip list

      - name: Run login script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python AngelFut.py
   
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add and commit files
        run: |
          git add -A
          git commit -m "Auto-commit CSV, TXT, JSON, and log files" || true
          git push origin main || true
